sudo: required
language: python
services:
- docker
before_install:
- docker build -t makerdao/pg-graphql .
script:
- "./test.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: WSdiMkrNFaXv49vL0Faix3uaNicLUt82GRTZt/mVn5aL4T7QhlMFJ+8xE8OqDZp6373Gz5E3HTP8JNaC7BcypmhU6V0od5+6QePeVIN+OJRMmlZeNINnc9r4Eljd9CeuLc8pu6K5e9oubtoPmKjJABlGOZEpVbAFuDEMix2KY7FJrWPeJBOvvxTu3Sb8Kkuw4ihGMMMJwyjhFCDJutYvpSJygiZaTX5/LsT69zjoj1Y/hpkThzo5nQNNHtZ8MuDuT4nuxThCVV9trvbZtm0WL8zf737nfbVYuS7ZtkOIeFse7Ge8mpejG/zJZ7IYR78mICneHGm8aextEOfPowD0YIHNawReMeZg7ALNgGJ7wTEZnfTX02f3sPLaGMyvGc2fepBMJRaCOuS+X0zLLKhM9oUKB/pNFZyQLOLeqIQri6cP4ca4RfscSK7ocL5YXpafXAgwjp/7PeVMYonwXWDceNqawaBqm6r22oxO00NTm9UlerjvpcNtZZClw9hDgHFRe7LDyF4Lq1rrTIcpOsqzWA5ebVO16z3SS3pVrZomqGPpVT8gthYVp7CuCouWyibXIXJpK/mZFNRgws3cdMJ7ZbVXIpLLyH4wG7zcwUoSsafHnbDB5O2K+wXhKTrENJ0YaH1ZCQPOEvB4fVnDl9deDbN/UjfhPPx7NzJyLaKdVFM=
  - secure: nKTJUIChVnF8APfWZ1X76yRApXv7AXJue7fO5brqpYp7LPFw5sZIF/wKDud72//uMOEDzQxGj9ah6OcXSwgnZrqYlLcsnyPkOUloBvvd4VF/aXZGROpOGps5n7mAsjEWQKPu4KtwX0Zh+NMiaQ/peKtRzoUqBrv498tluugqVjFwi340LSr3AdcRMDWqnvY845OlUgz2UxZ/wEigggzzCXK1BUT7scg5CAGqrkmYcUhti6Yli2cpFNA6juU/FP5/VVNdzD62C2+GId1zp3AN9sphSt6ilN9gmgRFsnb0pF4WV11xgH5uQnsiOroTnLq8xsUonrlf4va4AAwjnHoK1rueEFvTqoUtr68uqYgUHkglqmviZKatJluA+cqzjCLjcELjhfZWL8NFcZAmYb3IJ7Yvq3cN1OTKbKolhvDTwPOYogx8zE8s3C81Un/+ZV6s5mFF492TuOBuQmPJ0JDqdENeRhPa0DascybHBOooqTBJxRgYJtyZWzWbZe9D6NzHbVSZqKxgKTuJBzamTWcUDh5XHN2cIrBtgRkNH6u46Xi9RCWoo/6cMFrHx4u/y4ruhm8hEy3rOWVLq04M1w6WFA5l5u5k4c1mi/Ki2UhBHpIxZDGiggypni0SWGW2qG6kYo7qTJBqRzeRBIGQZeAedKXW6DRDtrzzAdYR1k8w6sY=
