version: "3.2"
services:
  sync:
    image: makerdao/pg-graphql
    container_name: sync
    volumes:
      - $ENV_FILE:/opt/pg-graphql/.env
    command: >
      bash -c "ENV=/opt/pg-graphql/.env npm run sync"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  sync100:
    image: makerdao/pg-graphql
    container_name: sync100
    volumes:
      - $ENV_FILE:/opt/pg-graphql/.env
    command: >
      bash -c "ENV=/opt/pg-graphql/.env npm run sync100"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  subscribe:
    image: makerdao/pg-graphql
    container_name: subscribe
    volumes:
      - $ENV_FILE:/opt/pg-graphql/.env
    command: >
      bash -c "ENV=/opt/pg-graphql/.env npm run subscribe"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  graphql:
    image: makerdao/pg-graphql
    container_name: graphql
    ports:
      - 4000:4000
    volumes:
      - $ENV_FILE:/opt/pg-graphql/.env
    command: >
      bash -c "ENV=/opt/pg-graphql/.env npm run graphql"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
